apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-version
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-version
    spec:
      containers:
      - name: docker-version
        image: ustabsreg.azurecr.io/docker-version:latest
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: registrypullsecret


---
apiVersion: v1
kind: Service
metadata:
  name: docker-version-service
spec:
  type: NodePort
  selector:
    app: docker-version
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 31862
