apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockertime
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dockertime
    spec:
      containers:
      - name: dockertime
        image: ustabsreg.azurecr.io/dockerbuild:latest
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: registrypullsecret


---
apiVersion: v1
kind: Service
metadata:
  name: dockertime-service
spec:
  type: NodePort
  selector:
    app: dockertime
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 31862
