FROM node:8
USER root
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN apt-get install curl &&\
	curl -sL https://deb.nodesource.com/setup 10.x|bash - &&\
	apt-get install -y nodejs &&\
	apt-get install -y npm &&\
	npm install
EXPOSE 3000
CMD node index.js